---
  all:
    hosts:
    children:
      app:
        hosts:
          host1:
            ansible_host: 10.116.0.3
      database:
        hosts:
          host2:
            ansible_host: 10.116.0.4