---
- name: Create a file
  hosts: localhost
  tasks:
    - name: Create a file under /tmp folder
      file:
        path: /tmp/file1
        state: touch
        mode: u+rwx,g+rwx,o+r
    - name: Create another file under /tmp folder
      file:
        path: /tmp/file2
        state: touch
        mode: u+rwx,g+rwx,o+r
