---
- name: Install Apache on Centos 7
  hosts: all
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: installed
    - name: Start and Enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes
